# Generated by Django 3.0.1 on 2020-01-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191230_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtracker',
            name='Bug_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
